/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_NewElectric_app11_CanAndSer
#define _Included_com_NewElectric_app11_CanAndSer
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_com_NewElectric_app11_CanAndSer_openCan
  (JNIEnv *, jclass);

JNIEXPORT jobject JNICALL Java_com_NewElectric_app11_CanAndSer_openSer
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
